#!/usr/bin/env bash

set -e

CONFIG="install.conf.yaml"
BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

cd "${BASEDIR}"

# submodules
ANTIGEN_DIR="submodules/antigen"
DOTBOT_DIR="submodules/dotbot"
TPM_DIR="submodules/tpm"

git -C "${DOTBOT_DIR}" submodule sync --quiet --recursive
git submodule update --init --recursive "${DOTBOT_DIR}"
git submodule update --init --recursive "${ANTIGEN_DIR}"
git submodule update --init --recursive "${TPM_DIR}"

DOTBOT_BIN="bin/dotbot"
"${BASEDIR}/${DOTBOT_DIR}/${DOTBOT_BIN}" -d "${BASEDIR}" -c "${CONFIG}" "${@}"
